Repository fossnsbm/Privacy-Dashboad, pull requests merged in 2021-02, with the labels that each got.

#49 Malaka
  package-lock.json
  package.json
  src/Components/pages/about/aboutStyle.css
  src/Components/pages/about/formAndSlide.jsx
Labels: enhancement

#61 Ruchira
  src/Components/pages/about/aboutStyle.css
  src/Components/pages/about/formAndSlide.jsx
Labels: UI Developing

#60 Prineth
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/NavBar/Nav.jsx
  src/Components/pages/RSVP/RSVPapp.jsx
  src/Components/pages/RSVP/RSVPchart.jsx
  src/Components/pages/RSVP/RSVPstyle.css
  src/Components/pages/event404/event404.jsx
  src/Components/pages/forum/forum.jsx
  src/Components/pages/forum/forumChart.jsx
  src/Components/pages/forum/forumStyle.css
  src/Components/pages/ketchUp/ketchUp.jsx
  src/Components/pages/mailServer/mailServer.css
  src/Components/pages/mailServer/mailServer.jsx
  src/Components/pages/mailServer/mailServerChart.jsx
Labels: UI Developing

#62 The issues in Footer has corrected and card components has been updated
  src/App.css
  src/App.js
  src/Components/Card/Card.jsx
  src/Components/Card/CardItem.jsx
  src/Components/Card/CardStyle.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
Labels: UI Developing

#63 Stable with Card Icons
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Components/Card/Card.jsx
  src/Components/Card/CardItem.jsx
  src/Components/Card/CardStyle.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/NavBar/Nav.jsx
  src/Components/pages/RSVP/RSVPapp.jsx
  src/Components/pages/RSVP/RSVPchart.jsx
  src/Components/pages/RSVP/RSVPstyle.css
  src/Components/pages/about/aboutStyle.css
  src/Components/pages/about/formAndSlide.jsx
  src/Components/pages/event404/event404.jsx
  src/Components/pages/forum/forum.jsx
  src/Components/pages/forum/forumChart.jsx
  src/Components/pages/forum/forumStyle.css
  src/Components/pages/ketchUp/ketchUp.jsx
  src/Components/pages/mailServer/mailServer.css
  src/Components/pages/mailServer/mailServer.jsx
  src/Components/pages/mailServer/mailServerChart.jsx
Labels: UI Developing

#64 Updated the Blog Content
  src/Components/pages/blog/Blog.jsx
Labels: content writing

#65 Wrote the content for About page
  src/Components/pages/about/content.jsx
Labels: content writing

#71 Fixed the problem of the dropdown menu in the navigation bar and added Card click redirect
  src/App.js
  src/Components/Card/CardItem.jsx
  src/Components/NavBar/Nav.jsx
  src/Components/pages/about/content.jsx
  src/Components/pages/landingPage/Card/Card.jsx
  src/Components/pages/landingPage/Card/CardItem.jsx
  src/Components/pages/landingPage/Card/CardStyle.css
  src/Components/pages/landingPage/Content/Content.css
  src/Components/pages/landingPage/Content/Content.jsx
  src/Components/pages/landingPage/LandingPage.jsx
  src/routes.jsx
Labels: UI Developing
